rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

before_script: "./spec/ci/before_script"

script: "./spec/ci/script"

env:
  # - RADIANT_VERSION=0.9.1 DB=mysql
  # - RADIANT_VERSION=0.9.1 DB=postgres
  - RADIANT_VERSION=1.0.0 DB=mysql
  - RADIANT_VERSION=1.0.0 DB=postgres
  - RADIANT_VERSION=1.1.0.alpha DB=mysql
  - RADIANT_VERSION=1.1.0.alpha DB=postgres

# matrix:
#  exclude:
#    - rvm: 1.9.2
#      env: RADIANT_VERSION=0.9.1 DB=mysql
#    - rvm: 1.9.2
#      env: RADIANT_VERSION=0.9.1 DB=postgres
#    - rvm: 1.9.3
#      env: RADIANT_VERSION=0.9.1 DB=mysql
#    - rvm: 1.9.3
#      env: RADIANT_VERSION=0.9.1 DB=postgres

notifications:
  recipients:
    - git@johnmuhl.com
  irc: "irc.freenode.org#radiantcms"
